/*jslint vars: true, plusplus: true, devel: true, nomen: true, regexp: true, indent: 4, maxerr: 50 */
/*global $, Folder, File, app */

$.__bodymovin.bm_reportsEffectMessages = (function () {
    
    var rendererTypes = $.__bodymovin.bm_reportRendererTypes;
    var messageTypes = $.__bodymovin.bm_reportMessageTypes;
    var builderTypes = $.__bodymovin.bm_reportBuilderTypes;

    var effectsMessages = {
        'ADBE AUX CHANNEL EXTRACT': { name: '3D Channel Extract', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE DEPTH MATTE': { name: 'Depth Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE DEPTH FIELD': { name: 'Depth of Field', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'EXtractoR': { name: 'EXtractoR', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE FOG_3D': { name: 'Fog 3D', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE ID MATTE': { name: 'ID Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'IDentifier': { name: 'IDentifier', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Reverse': { name: 'Backwards', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud BT': { name: 'Bass & Treble', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Delay': { name: 'Delay', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud_Flange': { name: 'Flange & Chorus', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud HiLo': { name: 'High-Low Pass', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Modulator': { name: 'Modulator', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Param EQ': { name: 'Parametric EQ', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Reverb': { name: 'Reverb', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Stereo Mixer': { name: 'Stereo Mixer', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Aud Tone': { name: 'Tone', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Bilateral': { name: 'Bilateral Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Camera Lens Blur': { name: 'Camera Lens Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE CameraShakeDeblur': { name: 'Camera-Shake Deblur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS CrossBlur': { name: 'CC Cross Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Radial Blur': { name: 'CC Radial Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Radial Fast Blur': { name: 'CC Radial Fast Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Vector Blur': { name: 'CC Vector Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Channel Blur': { name: 'Channel Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Compound Blur': { name: 'Compound Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Motion Blur': { name: 'Directional Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Box Blur2': { name: 'Fast Box Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Gaussian Blur 2': { name: 'Gaussian Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Radial Blur': { name: 'Radial Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Sharpen': { name: 'Sharpen', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Smart Blur': { name: 'Smart Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Unsharp Mask2': { name: 'Unsharp Mask', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Arithmetic': { name: 'Arithmetic', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Blend': { name: 'Blend', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Calculations': { name: 'Calculations', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Composite': { name: 'CC Composite', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Channel Combiner': { name: 'Channel Combiner', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Compound Arithmetic': { name: 'Compound Arithmetic', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Invert': { name: 'Invert', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Minimax': { name: 'Minimax', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Remove Color Matting': { name: 'Remove Color Matting', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Set Channels': { name: 'Set Channels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Set Matte3': { name: 'Set Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Shift Channels': { name: 'Shift Channels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Solid Composite': { name: 'Solid Composite', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CINEMA 4D Effect': { name: 'CINEWARE', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AutoColor': { name: 'Auto Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AutoContrast': { name: 'Auto Contrast', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AutoLevels': { name: 'Auto Levels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Black&White': { name: 'Black & White', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Brightness & Contrast 2': { name: 'Brightness & Contrast', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Broadcast Colors': { name: 'Broadcast Colors', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS Color Neutralizer': { name: 'CC Color Neutralizer', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Color Offset': { name: 'CC Color Offset', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS Kernel': { name: 'CC Kernel', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Toner': { name: 'CC Toner', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Change Color': { name: 'Change Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Change To Color': { name: 'Change to Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE CHANNEL MIXER': { name: 'Channel Mixer', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Balance 2': { name: 'Color Balance', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Balance (HLS)': { name: 'Color Balance (HLS)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Link': { name: 'Color Link', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Deflicker': { name: 'Color Stabilizer', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Colorama': { name: 'Colorama', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE CurvesCustom': { name: 'Curves', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Equalize': { name: 'Equalize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Exposure2': { name: 'Exposure', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Gamma/Pedestal/Gain2': { name: 'Gamma/Pedestal/Gain', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE HUE SATURATION': { name: 'Hue/Saturation', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Leave Color': { name: 'Leave Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Easy Levels2': { name: 'Levels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Pro Levels2': { name: 'Levels (Individual Controls)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Lumetri': { name: 'Lumetri Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PhotoFilterPS': { name: 'Photo Filter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PS Arbitrary Map': { name: 'PS Arbitrary Map', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE SelectiveColor': { name: 'Selective Color', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE ShadowHighlight': { name: 'Shadow/Highlight', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Tint': { name: 'Tint', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Tritone': { name: 'Tritone', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Vibrance': { name: 'Vibrance', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE BEZMESH': { name: 'Bezier Warp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Bulge': { name: 'Bulge', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Bend It': { name: 'CC Bend It', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Bender': { name: 'CC Bender', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Blobbylize': { name: 'CC Blobbylize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Flo Motion': { name: 'CC Flo Motion', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Griddler': { name: 'CC Griddler', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Lens': { name: 'CC Lens', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Page Turn': { name: 'CC Page Turn', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Power Pin': { name: 'CC Power Pin', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Ripple Pulse': { name: 'CC Ripple Pulse', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Slant': { name: 'CC Slant', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Smear': { name: 'CC Smear', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Split': { name: 'CC Split', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Split 2': { name: 'CC Split 2', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Tiler': { name: 'CC Tiler', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Corner Pin': { name: 'Corner Pin', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Upscale': { name: 'Detail-preserving Upscale', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Displacement Map': { name: 'Displacement Map', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE LIQUIFY': { name: 'Liquify', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Magnify': { name: 'Magnify', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE MESH WARP': { name: 'Mesh Warp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Mirror': { name: 'Mirror', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Offset': { name: 'Offset', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Optics Compensation': { name: 'Optics Compensation', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Polar Coordinates': { name: 'Polar Coordinates', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE RESHAPE': { name: 'Reshape', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Ripple': { name: 'Ripple', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Rolling Shutter': { name: 'Rolling Shutter Repair', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE SCHMEAR': { name: 'Smear', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Spherize': { name: 'Spherize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Geometry2': { name: 'Transform', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Turbulent Displace': { name: 'Turbulent Displace', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Twirl': { name: 'Twirl', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE WRPMESH': { name: 'Warp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE SubspaceStabilizer': { name: 'Warp Stabilizer VFX', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Wave Warp': { name: 'Wave Warp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Point3D Control': { name: '3D Point Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Angle Control': { name: 'Angle Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Checkbox Control': { name: 'Checkbox Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Control': { name: 'Color Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Layer Control': { name: 'Layer Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Point Control': { name: 'Point Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Slider Control': { name: 'Slider Control', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE 4ColorGradient': { name: '4-Color Gradient', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Lightning 2': { name: 'Advanced Lightning', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AudSpect': { name: 'Audio Spectrum', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AudWave': { name: 'Audio Waveform', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Laser': { name: 'Beam', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Glue Gun': { name: 'CC Glue Gun', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Light Burst 2.5': { name: 'CC Light Burst 2.5', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Light Rays': { name: 'CC Light Rays', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Light Sweep': { name: 'CC Light Sweep', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS Threads': { name: 'CC Threads', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Cell Pattern': { name: 'Cell Pattern', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Checkerboard': { name: 'Checkerboard', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Circle': { name: 'Circle', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE ELLIPSE': { name: 'Ellipse', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Eyedropper Fill': { name: 'Eyedropper Fill', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Fill': { name: 'Fill', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Fractal': { name: 'Fractal', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Ramp': { name: 'Gradient Ramp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Grid': { name: 'Grid', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Lens Flare': { name: 'Lens Flare', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Paint Bucket': { name: 'Paint Bucket', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Radio Waves': { name: 'Radio Waves', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Scribble Fill': { name: 'Scribble', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Stroke': { name: 'Stroke', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Vegas': { name: 'Vegas', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Write-on': { name: 'Write-on', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Spill2': { name: 'Advanced Spill Suppressor', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Simple Wire Removal': { name: 'CC Simple Wire Removal', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Difference Key': { name: 'Color Difference Key', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Range': { name: 'Color Range', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Difference Matte2': { name: 'Difference Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Extract': { name: 'Extract', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE ATG Extract': { name: 'Inner/Outer Key', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE KeyCleaner': { name: 'Key Cleaner', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'Keylight 906': { name: 'Keylight (1.2)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Linear Color Key2': { name: 'Linear Color Key', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Matte Choker': { name: 'Matte Choker', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ISL MochaShapeImporter': { name: 'mocha shape', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE RefineRBMatte': { name: 'Refine Hard Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE RefineMatte2': { name: 'Refine Soft Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Simple Choker': { name: 'Simple Choker', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'VISINF Grain Implant': { name: 'Add Grain', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Dust & Scratches': { name: 'Dust & Scratches', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Fractal Noise': { name: 'Fractal Noise', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'VISINF Grain Duplication': { name: 'Match Grain', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Median': { name: 'Median', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise': { name: 'Noise', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise Alpha2': { name: 'Noise Alpha', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise HLS2': { name: 'Noise HLS', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise HLS Auto2': { name: 'Noise HLS Auto', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'VISINF Grain Removal': { name: 'Remove Grain', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE AIF Perlin Noise 3D': { name: 'Turbulent Noise', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Basic 3D': { name: 'Basic 3D', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Basic Text2': { name: 'Basic Text', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Key': { name: 'Color Key', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Fast Blur': { name: 'Fast Blur (Legacy)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Gaussian Blur': { name: 'Gaussian Blur (Legacy)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Lightning': { name: 'Lightning', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Luma Key': { name: 'Luma Key', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Path Text': { name: 'Path Text', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Reduce Interlace Flicker': { name: 'Reduce Interlace Flicker', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Spill Suppressor': { name: 'Spill Suppressor', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE 3D Tracker': { name: '3D Camera Tracker', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE 3D Glasses2': { name: '3D Glasses', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Bevel Alpha': { name: 'Bevel Alpha', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Bevel Edges': { name: 'Bevel Edges', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Cylinder': { name: 'CC Cylinder', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Environment': { name: 'CC Environment', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Sphere': { name: 'CC Sphere', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Spotlight': { name: 'CC Spotlight', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Drop Shadow': { name: 'Drop Shadow', messages:[
            {type: messageTypes.ERROR, renderers:[rendererTypes.IOS, rendererTypes.ANDROID]},
            {type: messageTypes.WARNING, renderers:[rendererTypes.BROWSER], builder: builderTypes.FILTER_SIZE},
        ]},
        'ADBE Radial Shadow': { name: 'Radial Shadow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC CardDanceCam': { name: 'Card Dance', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Caustics': { name: 'Caustics', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Ball Action': { name: 'CC Ball Action', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Bubbles': { name: 'CC Bubbles', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Drizzle': { name: 'CC Drizzle', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Hair': { name: 'CC Hair', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Mr. Mercury': { name: 'CC Mr. Mercury', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Particle Systems II': { name: 'CC Particle Systems II', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Particle World': { name: 'CC Particle World', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Pixel Polly': { name: 'CC Pixel Polly', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CSRainfall': { name: 'CC Rainfall', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Scatterize': { name: 'CC Scatterize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CSSnowfall': { name: 'CC Snowfall', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Star Burst': { name: 'CC Star Burst', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Foam': { name: 'Foam', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Playgnd': { name: 'Particle Playground', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Shatter': { name: 'Shatter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC Wave World': { name: 'Wave World', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Brush Strokes': { name: 'Brush Strokes', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Cartoonify': { name: 'Cartoon', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS BlockLoad': { name: 'CC Block Load', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Burn Film': { name: 'CC Burn Film', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Glass': { name: 'CC Glass', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS HexTile': { name: 'CC HexTile', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Kaleida': { name: 'CC Kaleida', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Mr. Smoothie': { name: 'CC Mr. Smoothie', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Plastic': { name: 'CC Plastic', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC RepeTile': { name: 'CC RepeTile', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Threshold': { name: 'CC Threshold', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Threshold RGB': { name: 'CC Threshold RGB', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS Vignette': { name: 'CC Vignette', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Emboss': { name: 'Color Emboss', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Emboss': { name: 'Emboss', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Find Edges': { name: 'Find Edges', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Glo2': { name: 'Glow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Mosaic': { name: 'Mosaic', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Tile': { name: 'Motion Tile', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Posterize': { name: 'Posterize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Roughen Edges': { name: 'Roughen Edges', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Scatter': { name: 'Scatter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Strobe': { name: 'Strobe Light', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Texturize': { name: 'Texturize', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Threshold2': { name: 'Threshold', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'SYNTHAP CF Color Finesse 2': { name: 'SA Color Finesse 3', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Numbers2': { name: 'Numbers', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Timecode': { name: 'Timecode', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Force Motion Blur': { name: 'CC Force Motion Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Wide Time': { name: 'CC Wide Time', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Echo': { name: 'Echo', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE OFMotionBlur': { name: 'Pixel Motion Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Posterize Time': { name: 'Posterize Time', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Difference': { name: 'Time Difference', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Time Displacement': { name: 'Time Displacement', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Timewarp': { name: 'Timewarp', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Block Dissolve': { name: 'Block Dissolve', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'APC CardWipeCam': { name: 'Card Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Glass Wipe': { name: 'CC Glass Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Grid Wipe': { name: 'CC Grid Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Image Wipe': { name: 'CC Image Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Jaws': { name: 'CC Jaws', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Light Wipe': { name: 'CC Light Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CS LineSweep': { name: 'CC Line Sweep', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Radial ScaleWipe': { name: 'CC Radial ScaleWipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Scale Wipe': { name: 'CC Scale Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Twister': { name: 'CC Twister', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC WarpoMatic': { name: 'CC WarpoMatic', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Gradient Wipe': { name: 'Gradient Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE IRIS_WIPE': { name: 'Iris Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Linear Wipe': { name: 'Linear Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Radial Wipe': { name: 'Radial Wipe', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Venetian Blinds': { name: 'Venetian Blinds', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Apply Color LUT2': { name: 'Apply Color LUT', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Overbrights': { name: 'CC Overbrights', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Cineon Converter2': { name: 'Cineon Converter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE ProfileToProfile': { name: 'Color Profile Converter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE GROW BOUNDS': { name: 'Grow Bounds', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Compander': { name: 'HDR Compander', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE HDR ToneMap': { name: 'HDR Highlight Compression', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Paint': { name: 'Paint', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Samurai': { name: 'Roto Brush & Refine Edge', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE FreePin3': { name: 'Puppet', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE RefineMatte': { name: 'Refine Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE 3D Glasses': { name: '3D Glasses (Obsolete)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Alpha Levels2': { name: 'Alpha Levels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Alpha Levels3': { name: 'Alpha Levels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Apply Color LUT': { name: 'Apply Color LUT', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Brightness & Contrast': { name: 'Brightness & Contrast', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Box Blur': { name: 'Box Blur', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Cineon Converter': { name: 'Cineon Converter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Color Balance': { name: 'Color Balance', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC PS Classic': { name: 'CC PS Classic (obsolete)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC PS LE Classic': { name: 'CC PS LE Classic (obsolete)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Rain': { name: 'CC Rain', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Snow': { name: 'CC Snow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Time Blend': { name: 'CC Time Blend', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'CC Time Blend FX': { name: 'CC Time Blend FX', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Exposure': { name: 'Exposure', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Easy Levels': { name: 'Levels', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Pro Levels': { name: 'Levels (Individual Controls)', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise Alpha': { name: 'Noise Alpha', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise HLS': { name: 'Noise HLS', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Noise HLS Auto': { name: 'Noise HLS Auto', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Bevel Emboss': { name: 'Photoshop Bevel And Emboss', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Drop Shadow': { name: 'Photoshop Drop Shadow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Inner Glow': { name: 'Photoshop Inner Glow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Inner Shadow': { name: 'Photoshop Inner Shadow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Outer Glow': { name: 'Photoshop Outer Glow', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE PSL Solid Fill': { name: 'Photoshop Solid Fill', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Photo Filter': { name: 'Photo Filter', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Set Matte2': { name: 'Set Matte', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Three-Way Color Corrector': { name: 'Three-Way Color Corrector', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Threshold': { name: 'Threshold', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Geometry': { name: 'Transform', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Unsharp Mask': { name: 'Unsharp Mask', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
        'ADBE Vector Paint': { name: 'Vector Paint', messages:[{type: messageTypes.ERROR, renderers:[rendererTypes.BROWSER, rendererTypes.IOS, rendererTypes.ANDROID]}]},
    }

    return effectsMessages;
    
}());
