nodeLinker: node-modules
npmPreapprovedPackages:
  - eslint-config-taeyoon@0.2.2
plugins:
  - path: .yarn/plugins/@echoscript-yarn-plugin.cjs
    spec: "https://raw.githubusercontent.com/taeyoon0137/echoscript/1af7b5dd51c80fc07c80a1f7666f5a3f7ca8f28a/packages/plugin/plugin/bundle.js"
